export const tasksUrl: string = '/tasks'
export const userUrl: string = '/users'
export const pathToHome: string = '/'
export const pathToProfile: string = '/profile'
export const pathToLogin: string = '/login'
export const pathToRegister: string = '/register'
export const pathToTask: string = '/tasks'
export const pathToCreateNewTask: string = `${pathToTask}/create-new`
export const pathToTaskCard = `${pathToTask}/task/`
