export const tasksUrl: string = '/tasks'
export const userUrl: string = '/users'
export const pathToHome: string = '/'
export const pathToProfile: string = '/profile'
export const pathToLogin: string = '/login'
export const pathToRegister: string = '/register'
